#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Pizza.Mvc;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/EditorTemplates/Html.cshtml")]
    public partial class _Views_Shared_EditorTemplates_Html_cshtml_ : System.Web.Mvc.WebViewPage<string>
    {
        public _Views_Shared_EditorTemplates_Html_cshtml_()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Shared\EditorTemplates\Html.cshtml"
Write(Html.TextAreaFor(x => Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    $(function () {\r\n        $(\'#");

            
            #line 7 "..\..\Views\Shared\EditorTemplates\Html.cshtml"
       Write(ViewData.TemplateInfo.GetFullHtmlFieldId(string.Empty));

            
            #line default
            #line hidden
WriteLiteral("\').tinymce({\r\n            script_url: \'");

            
            #line 8 "..\..\Views\Shared\EditorTemplates\Html.cshtml"
                    Write(Url.Content("~/Scripts/tinymce/tinymce.js"));

            
            #line default
            #line hidden
WriteLiteral(@"',
            theme: ""modern"",
            height: 250,
            class: ""form-control"",
            paste_data_images: true,
            plugins: [
                ""advlist autolink lists link image charmap print preview hr anchor pagebreak"",
                ""searchreplace wordcount visualblocks visualchars code fullscreen"",
                ""insertdatetime media nonbreaking save table contextmenu directionality"",
                ""emoticons template paste textcolor""
            ],
            toolbar1: ""insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"",
            toolbar2: ""print preview media | forecolor backcolor emoticons"",
            image_advtab: true,
            templates: [
                { title: ""Test template 1"", content: ""Test 1"" },
                { title: ""Test template 2"", content: ""Test 2"" }
            ]
        });
    });
</script>
");

        }
    }
}
#pragma warning restore 1591
