//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizza.Mvc.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UiTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pizza.Mvc.Resources.UiTexts", typeof(UiTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password Form.
        /// </summary>
        public static string ChangePasswordPage_Title {
            get {
                return ResourceManager.GetString("ChangePasswordPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePasswportPage_Button_Submit {
            get {
                return ResourceManager.GetString("ChangePasswportPage_Button_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application error.
        /// </summary>
        public static string Dialog_ApplicationError_Title {
            get {
                return ResourceManager.GetString("Dialog_ApplicationError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        public static string Dialog_ApplicationError_UnknownErrorText {
            get {
                return ResourceManager.GetString("Dialog_ApplicationError_UnknownErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this record?.
        /// </summary>
        public static string Dialog_DeleteRowConfirmation_Question {
            get {
                return ResourceManager.GetString("Dialog_DeleteRowConfirmation_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete confirmation.
        /// </summary>
        public static string Dialog_DeleteRowConfirmation_Title {
            get {
                return ResourceManager.GetString("Dialog_DeleteRowConfirmation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string DialogButton_Close {
            get {
                return ResourceManager.GetString("DialogButton_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string DialogButton_No {
            get {
                return ResourceManager.GetString("DialogButton_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string DialogButton_Yes {
            get {
                return ResourceManager.GetString("DialogButton_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select value.
        /// </summary>
        public static string Editor_DropDown_EmptyValue {
            get {
                return ResourceManager.GetString("Editor_DropDown_EmptyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string FormButton_Create {
            get {
                return ResourceManager.GetString("FormButton_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string FormButton_Save {
            get {
                return ResourceManager.GetString("FormButton_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string GridButton_Clear {
            get {
                return ResourceManager.GetString("GridButton_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string GridButton_Create {
            get {
                return ResourceManager.GetString("GridButton_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string GridButton_Delete {
            get {
                return ResourceManager.GetString("GridButton_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string GridButton_Details {
            get {
                return ResourceManager.GetString("GridButton_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string GridButton_Edit {
            get {
                return ResourceManager.GetString("GridButton_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string GridSearch_DropDown_All {
            get {
                return ResourceManager.GetString("GridSearch_DropDown_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to list.
        /// </summary>
        public static string Link_BackToIndex {
            get {
                return ResourceManager.GetString("Link_BackToIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LoginPage_Button_Login {
            get {
                return ResourceManager.GetString("LoginPage_Button_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a local account to log in..
        /// </summary>
        public static string LoginPage_Message {
            get {
                return ResourceManager.GetString("LoginPage_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LoginPage_Title {
            get {
                return ResourceManager.GetString("LoginPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new item form.
        /// </summary>
        public static string ViewTitle_Create {
            get {
                return ResourceManager.GetString("ViewTitle_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item details form.
        /// </summary>
        public static string ViewTitle_Details {
            get {
                return ResourceManager.GetString("ViewTitle_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit item form.
        /// </summary>
        public static string ViewTitle_Edit {
            get {
                return ResourceManager.GetString("ViewTitle_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items list.
        /// </summary>
        public static string ViewTitle_Index {
            get {
                return ResourceManager.GetString("ViewTitle_Index", resourceCulture);
            }
        }
    }
}
