using Pizza.Contracts.Presentation.Operations.Results;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Pizza.Mvc;
    
    #line 1 "..\..\Views\Shared\_Paginator.cshtml"
    using Pizza.Mvc.HtmlHelpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Paginator.cshtml")]
    public partial class _Views_Shared__Paginator_cshtml : System.Web.Mvc.WebViewPage<PagingInfo>
    {
        public _Views_Shared__Paginator_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Shared\_Paginator.cshtml"
 if (Model.TotalPages > 0)
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"float-left full-row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"centered-content paginator\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 8 "..\..\Views\Shared\_Paginator.cshtml"
       Write(Html.PageLinks(Model, x => Url.Action((string)this.ViewContext.RouteData.Values["action"], new { pageNumber = x })));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n");

            
            #line 11 "..\..\Views\Shared\_Paginator.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
