#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Pizza.Mvc;
    
    #line 1 "..\..\Views\Shared\Details.cshtml"
    using Pizza.Mvc.HtmlHelpers;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Shared\Details.cshtml"
    using Pizza.Mvc.Resources;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Details.cshtml")]
    public partial class _Views_Shared_Details_cshtml : System.Web.Mvc.WebViewPage<Pizza.Contracts.IDetailsModelBase>
    {
        public _Views_Shared_Details_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<h2>\r\n");

WriteLiteral("    ");

            
            #line 6 "..\..\Views\Shared\Details.cshtml"
Write(ViewBag.PageTitle);

            
            #line default
            #line hidden
WriteLiteral("\r\n</h2>\r\n\r\n<div>\r\n    <dl");

WriteLiteral(" class=\"dl-horizontal\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 11 "..\..\Views\Shared\Details.cshtml"
   Write(Html.ModelDisplay(Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </dl>\r\n</div>\r\n\r\n<p>\r\n");

WriteLiteral("    ");

            
            #line 16 "..\..\Views\Shared\Details.cshtml"
Write(Html.ActionLink(UiTexts.Link_BackToIndex, ScriptKeys.Index));

            
            #line default
            #line hidden
WriteLiteral("\r\n</p>\r\n");

        }
    }
}
#pragma warning restore 1591
